# Generated by Django 2.1.7 on 2019-03-11 14:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateField(default=datetime.date.today, verbose_name='Booking date from')),
                ('dateTo', models.DateField(default=datetime.date.today, verbose_name='Booking date to')),
                ('hotel', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='hotel_app.Hotel')),
                ('user', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
