# Generated by Django 2.1.7 on 2019-03-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
        ('hotel_app', '0003_auto_20190308_1053'),
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('customer', 'hotel')},
        ),
    ]
