# Generated by Django 2.1.7 on 2019-03-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('forename', models.CharField(default='', max_length=20, verbose_name='First Name')),
                ('surname', models.CharField(default='', max_length=20, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email')),
                ('phone', models.IntegerField(default=0, verbose_name='Phone')),
                ('address', models.CharField(default='', max_length=256, verbose_name='Home Address')),
                ('country', models.CharField(default='', max_length=256, verbose_name='Country')),
            ],
        ),
    ]
