# Generated by Django 2.1.7 on 2019-03-06 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('forename', models.CharField(default='', max_length=20, verbose_name='First Name')),
                ('surname', models.CharField(default='', max_length=20, verbose_name='Last Name')),
                ('phone', models.IntegerField(default=0, verbose_name='Phone')),
                ('address', models.CharField(default='', max_length=256, verbose_name='Home Address')),
                ('country', models.CharField(default='', max_length=256, verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
