# Generated by Django 2.1.7 on 2019-03-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='firstStreet',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='secondStreet',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipCode',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=256, verbose_name='Home Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='', max_length=256, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='forename',
            field=models.CharField(default='', max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(default='', max_length=20, verbose_name='Last Name'),
        ),
    ]
