# Generated by Django 2.1.7 on 2019-03-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=250, verbose_name='Name of Hotel')),
                ('property_city', models.CharField(default='', max_length=250, verbose_name='City of Hotel')),
                ('address', models.CharField(max_length=255, verbose_name='Address of Hotel')),
                ('petsAllowed', models.BooleanField(verbose_name='Pets Allowed')),
                ('pricePerNight', models.FloatField(verbose_name='Price per night')),
                ('averageRating', models.FloatField(verbose_name='Average Rating')),
                ('wifiAvailability', models.BooleanField(verbose_name='Wifi Availability')),
                ('parkingAvailability', models.BooleanField(verbose_name='Parking Availability')),
                ('latitudeCoordinates', models.FloatField(default=0.0, verbose_name='Latitude Coordinates')),
                ('longitudeCoordinates', models.FloatField(default=0.0, verbose_name='Longitude Coordinates')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together={('property_name', 'address', 'latitudeCoordinates', 'longitudeCoordinates')},
        ),
    ]
