# Generated by Django 2.1.7 on 2019-03-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='latitudeCoordinates',
            field=models.IntegerField(default=0, verbose_name='Latitude Coordinates'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitudeCoordinates',
            field=models.IntegerField(default=0, verbose_name='Longitude Coordinates'),
        ),
    ]
