# Generated by Django 2.1.7 on 2019-03-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='property_city',
            field=models.CharField(default='Munich', max_length=250, verbose_name='City of Hotel'),
        ),
    ]
