# Generated by Django 2.1.7 on 2019-03-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_auto_20190304_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitudeCoordinates',
            field=models.FloatField(default=0.0, verbose_name='Latitude Coordinates'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitudeCoordinates',
            field=models.FloatField(default=0.0, verbose_name='Longitude Coordinates'),
        ),
    ]
