# Generated by Django 2.1.7 on 2019-03-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_hotel_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='property_city',
            field=models.CharField(default='', max_length=250, verbose_name='City of Hotel'),
        ),
    ]
