


def createCustomerSeeds(request):
    data = [
    {forename: "Soheil",
    surname:"Gabunia",
    email:"soheil@gmail.com",
    phone:4567890987,
    address:Carretera,
    country:, },
    {forename:,
    surname:,
    email:,
    phone:,
    address:,
    country:,},
    {forename:,
    surname:,
    email:,
    phone:,
    address:,
    country:,},
    {forename:,
    surname:,
    email:,
    phone:,
    address:,
    country:,},
    {forename:,
    surname:,
    email:,
    phone:,
    address:,
    country:,},
    {forename:,
    surname:,
    email:,
    phone:,
    address:,
    country:,},
    {forename:,
    surname:,
    email:,
    phone:,
    address:,
    country:,},
    {forename:,
    surname:,
    email:,
    phone:,
    address:,
    country:,},
    {forename:,
    surname:,
    email:,
    phone:,
    address:,
    country:,},
    {forename:,
    surname:,
    email:,
    phone:,
    address:,
    country:,}
    ]

